language:generic

services:
  - docker

after_success:
  - docker build -t jdiaz67/user-wishlist .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jdiaz67/user-wishlist

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Jocelyn's User Wishlist
  env: Jocelynsuserwishlist-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "multi-container-wishlist-app-jd"
  bucket_path: "docker"
    on:
      branch: multi-cont-app